---
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.1.2
_src_path: gh:radio-aktywne/template-generic
accountname: radio-aktywne
description: assets 🎨
docs: true
docsurl: https://radio-aktywne.github.io/assets
projectname: assets
releases: false
reponame: assets
repourl: https://github.com/radio-aktywne/assets
