---
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.3
_src_path: gh:quickplates/generic
description: assets 🎨
docs: true
docsurl: https://radio-aktywne.github.io/assets
projectname: assets
username: radio-aktywne
